### ISSUE TITLE
Tika Server extraction is working

### ISSUE THREAD

**Issue by kswan** [backdrop-contrib/search_api_attachments#3]
This isn't really an issue, but I wanted to report that you can update the README since I can confirm that the module is working using the Tika server extraction. I am applying it to my production environment within the next week.

I am running Tika in a docker container by adding the section below to my docker-compose.yml.
```
 tika:
    image: apache/tika:latest-full
    restart: unless-stopped
    ports:
            - "127.0.0.1:9998:9998"
```

I applied one patch that is submitted on PR #2 .

I haven't tested any of the sub-modules either.
